### ISSUE TITLE
Link de la ayudantía

### ISSUE THREAD

**Issue by Tvergara** [marceloarenassaavedra/IIC2283-2-21#1]
Hola, no encontré el link a la grabación de la ayudantía, está subida en algún lado?

**Comment by marceloarenassaavedra** [comment]
Hola!

El link al video de la ayudantía ya está en la sección :

https://github.com/marceloarenassaavedra/IIC2283-2-21/tree/master/Ayudant%C3%ADas

En esta sección vamos a dejar todo el material de la ayudantía.

Saludos!
