### ISSUE TITLE
[Tarea 1] Intervalos de días en problema 2

### ISSUE THREAD

**Issue by benjaminlillo** [marceloarenassaavedra/IIC2283-2-21#12]
Hola! Tengo unas preguntas para el problema 2:

1. Si una empresa productora empieza a operar un día s_i, ¿Sigue produciendo hasta el infinito? Lo mismo para las consumidoras: si terminan de comprar un día e_j, ¿Todos los días anteriores a e_j podrán comprar?
2. ¿Podrán ocurrir todo tipo de casos en cuanto al traslapado de intervalos para la solución? Es decir, dada productora i y consumidora j que sean la solución al problema, puede pasar que s_i > e_j, s_i < e_j o que s_i = e_j?
3. ¿Se pueden "guardar" juguetes por varios días? ¿O necesariamente debo vender un juguete el mismo día que lo compro?

**Comment by PabloMessina** [comment]
Hola. Respondiendo a tus preguntas:
1.  Sí a ambas subpreguntas.
2. Sí, todo es posible. Obviamente, si la intersección es vacía, no tendría sentido comprar juguetes que después no vas a poder vender.
3. En teoría algunos días podrías comprar juguetes y decidir no vender, o viceversa. Si crees que eso te puede ayudar a aumentar las ganancias, lo dejo a tu criterio. Pero recuerda que cada empresa productora vende a lo más un juguete por día, y cada empresa consumidora compra a lo más un juguete por día. Si acumulas un stock de X juguetes, necesitarías X días para venderlos (uno por día).

**Comment by benjaminlillo** [comment]
Perfecto, gracias!
