### ISSUE TITLE
[Clases] Representación punto-valor

### ISSUE THREAD

**Issue by jgespinosa10** [marceloarenassaavedra/IIC2283-2-21#15]
Hola,

respecto de la última clase, me costo entender cómo funcionaba la representación punto-valor que a la que el profesor se refierió en la clase. En específico, no entendí cómo era la transformación y porque cumplía la propiedad de que:

si p = {(v_0, p(v_0)), ... , (v_n, p(v_n))}
y  q = {(v_0, q(v_0)), ... , (v_n, q(v_n))}
entonces

p*q = {(v_0, p(v_0) * q(v_0)), ... , (v_n, p(v_n) * q(v_n))}

¿Podrían explicar por favor? ¿Donde puedo buscarlo material complementario para entender?

**Comment by N9199** [comment]
Tengo una duda sobre tu duda, es sobre por qué
<img src="https://latex.codecogs.com/png.latex?p\cdot&space;q=\{(v_0,p(v_0)\cdot&space;q(v_0)),\ldots,(v_n,p(v_n)\cdot&space;q(v_n))\}" title="p\cdot q=\{(v_0,p(v_0)\cdot q(v_0)),\ldots,(v_n,p(v_n)\cdot q(v_n))\}" />
y
<img src="https://latex.codecogs.com/png.latex?p&plus;&space;q=\{(v_0,p(v_0)&plus;&space;q(v_0)),\ldots,(v_n,p(v_n)&plus;&space;q(v_n))\}" title="p+q=\{(v_0,p(v_0)+ q(v_0)),\ldots,(v_n,p(v_n)+ q(v_n))\}" />
no?

**Comment by jgespinosa10** [comment]
Hola! Si, me confundí escribiendolo jajaja

**Comment by marceloarenassaavedra** [comment]
> Hola,
> 
> respecto de la última clase, me costo entender cómo funcionaba la representación punto-valor que a la que el profesor se refierió en la clase. En específico, no entendí cómo era la transformación y porque cumplía la propiedad de que:
> 
> si p = {(v_0, p(v_0)), ... , (v_n, p(v_n))}
> y q = {(v_0, q(v_0)), ... , (v_n, q(v_n))}
> entonces
> 
> p*q = {(v_0, p(v_0) * q(v_0)), ... , (v_n, p(v_n) * q(v_n))}
> 
> ¿Podrían explicar por favor? ¿Donde puedo buscarlo material complementario para entender?

Dada una función `f(x)`, un par punto-valor `(a, f(a))` es un punto en la curva. Para el caso de un polinomio de grado `n-1` sabemos que `n` de estos puntos en el plano definen de manera única a la curva. Por ejemplo, dos puntos en el plano definen a una recta y tres puntos en el plano definen a una parábola. 

Como un ejemplo concreto, si tienes la recta `p(x) = 2x + 7`, entonces los siguientes pares punto-valor definen a `p(x)`:  `{(0,7), (1,9)}`. Puedes usar otras combinaciones para definir `p(x)`, incluso algunas que tengan más de dos pares: `{(-3,1), (0,7), (5,17), (10,27)}`.

 Supón ahora que tienes representaciones punto-valor de dos polinomios:

`p(x)` :  `{ (v_0, p(v_0)), ..., (v_{n-1}, p(v_{n-1})) }`
`q(x)` :  `{ (v_0, q(v_0)), ..., (v_{n-1}, q(v_{n-1})) }`

La pregunta aquí es cómo podrías calcular pares punto-valor para el polinomio `s(x) = p(x)*q(x)`. Dado que `s(v_0) = p(v_0)*q(v_0)`, se tiene entonces que `(v_0, p(v_0)*q(v_0))` es un par punto-valor para la función `s(x)`. Siguiendo con este razonamiento, obtenemos que todos los siguientes son pares punto-valor para el polinomio `s(x)`:

 `{ (v_0, p(v_0)*q(v_0)), ..., (v_{n-1}, p(v_{n-1})*q(v_{n-1})) }`

Si `p(x)` y `q(x)` son polinomios de grado `n-1`, entonces `s(x)` es un polinomio de grado `2n-2`, por lo que se necesita de al menos `2n-1` pares punto-valor para que quede definido de manera única. Para lograr esto, simplemente se pide que tengamos al menos `2n-1` pares punto-valor inicialmente para `p(x)` y `q(x)`, por ejemplo en este caso `2n` pares punto-valor para estos polinomios:

`p(x)` :  `{ (v_0, p(v_0)), ..., (v_{2n-1}, p(v_{2n-1})) }`
`q(x)` :  `{ (v_0, q(v_0)), ..., (v_{2n-1}, q(v_{2n-1})) }`

Y el cálculo de la representación de `s(x)` se hace como fue mencionado antes:

`s(x)` :  `{ (v_0, p(v_0)*q(v_0)), ..., (v_{2n-1}, p(v_{2n-1})*q(v_{2n-1})) }`

¿Queda más claro ahora?

Saludos!

**Comment by jgespinosa10** [comment]
Si! Con esto me quedó clarísimo! Muchas gracias
