### ISSUE TITLE
[Tarea 1][p1] Duda sobre tiempo ejecución y Output

### ISSUE THREAD

**Issue by Christian-Klempau** [marceloarenassaavedra/IIC2283-2-21#17]
Hola! Respecto a la pregunta 1 de la tarea, tengo una duda sobre el tiempo de ejecución (menor a 1 segundo):
Este tiempo es en el cual el programa de calcular:
- **cualquier** número del dominio
- el dominio **completo**
- un **rango** acotado dentro del dominio

Y respecto al output:
¿Este debe ser simplemente impreso en **consola**?

**Comment by N9199** [comment]
Hola, como dice en el enunciado del problema el input es solo un número del dominio y el tiempo de ejecución es para un input. Sobre la última pregunta ver #11 .

**Comment by Christian-Klempau** [comment]
Muchas gracias!

**Comment by Brocoleta** [comment]
Entonces para n = 10^18 deberia demorar 1 segundo?

**Comment by N9199** [comment]
> Entonces para n = 10^18 deberia demorar 1 segundo?

Si, debería demorar a lo más 1 segundo.
