### ISSUE TITLE
[Tarea 1] ¿Error en ejemplo pregunta 2? + restricción de sana competencia

### ISSUE THREAD

**Issue by benjaminlillo** [marceloarenassaavedra/IIC2283-2-21#18]
Hola! Hice a mano el input 1 de ejemplo de la pregunta 2 y me dio que el óptimo era de 3 y no de 5. ¿Es un error del enunciado?

![WhatsApp Image 2021-09-20 at 5 17 43 PM](https://user-images.githubusercontent.com/53795716/134077228-5de6727d-00dc-4ae0-aecb-9f9e33f38685.jpeg)

También tengo otra pregunta: ¿Solo se pueden trabajar con 1 productora y 1 consumidora en todo el proceso? ¿O esa restricción aplica solamente durante un día?

**Comment by PabloMessina** [comment]
Hola. Primero que todo, la combinación que escogiste te da ingreso 4, no 3, ya que son 4 días en común (días 1, 2, 3 y 4). Por el mismo motivo, la combinación p =2 y q = 7 te da ingreso 5, ya que tienen día en común (el día 1) y la diferencia de precios es 5.
![image](https://user-images.githubusercontent.com/6187545/134407939-177ad1d5-614e-42f5-8ebc-f3e43b3a91d8.png)

Sobre tu otra pregunta, sí, el problema se trata de encontrar el mejor par consumidor-productor que maximice tu ganancia. Es un solo par, no múltiples pares.

**Comment by benjaminlillo** [comment]
Ok entiendo, gracias!
