### ISSUE TITLE
Cámara de pizarra en grabaciones de clases

### ISSUE THREAD

**Issue by Taeval** [marceloarenassaavedra/IIC2283-2-21#2]
Será posible que grabaciones futuras de las clases muestren la pizarra en vez de las slides? Las slides están disponibles en este repositorio y las podemos descargar, pero también se anotan cosas importantes en la pizarra. En las grabaciones, la pizarra aparece solo en una esquina y en una ventana pequeña, lo que hace incómodo revisar las clases.

**Comment by marceloarenassaavedra** [comment]
Hola!

La mejor solución que nos ofrecen para este problema es usar Kaptivo para grabar el contenido de la pizarra durante la clase. Voy a ir dejando en el siguiente directorio estas grabaciones:

https://github.com/marceloarenassaavedra/IIC2283-2-21/tree/master/grabaciones%20pizarra

¿Esta solución es suficiente para el problema mencionado?

Saludos!

**Comment by Taeval** [comment]
La solución ayuda, permite ver mejor lo escrito en la pizarra, pero no se cuál es la frecuencia de las fotos que captura. ¿Qué pasaría si: se toma una foto, se escribe algo más en la pizarra, se borra todo para comenzar a ilustrar otra idea y se toma una nueva foto? En ese caso se perdería información de la pizarra. Lo ideal sería que se suba una grabación de lo que captura la cámara de la pizarra, que es la que aparece en la esquina en las grabaciones actuales, pero no se si Zoom permite eso. Pero gracias igual por la solución!

**Comment by marceloarenassaavedra** [comment]
Según entiendo la frecuencia de las fotos no está predeterminada, el sistema determina esto de acuerdo a lo que se vaya escribiendo en la pizarra (para no perder información). Pero por favor si en algún momento detectan que el sistema perdió información, me avisan para ver cómo solucionar este problema.

Saludos!
