### ISSUE TITLE
[Tarea 1] Librerías standard de Python3

### ISSUE THREAD

**Issue by jeschuwirth** [marceloarenassaavedra/IIC2283-2-21#22]
Aprovecho de repetir una duda que estaba en una issue cerrada y nunca se respondió #16.

Según la issue #6, solamente podemos utilizar las librerías standard de Python. ¿Esto incluye módulos como _math_ o _itertools_, es decir aquellas que estén en https://docs.python.org/?

**Comment by N9199** [comment]
Respondido en #6
