### ISSUE TITLE
[Tarea1] [P2] orden

### ISSUE THREAD

**Issue by ljrodriguez1** [marceloarenassaavedra/IIC2283-2-21#23]
Hola, quería saber si no es muy exigente el requisito de 5 segundos para la pregunta 2, cree un algoritmo con la complejidad esperada. y para n y m 10^4 me corre en 30 segundos :(

**Comment by PabloMessina** [comment]
Es posible que tengamos que reajustar el tiempo ligeramente (no sería la primera vez), pero tengan la seguridad de que va a haber tiempo suficiente para que una solución en python de referencia, con la complejidad recomendada, obtenga nota 7.0. Si la razón por la que tu solución se demora mucho es por algún error muy menor (forma de leer el input, etc.), eso lo podremos ver más adelante si es que nos pides recorrección. En todo caso, es muy raro que con 10^4 x log(10^4) operaciones se te demore 30 segundos. ¿Cuánto se te demora la solución cuadrática O(m x n) en ese mismo ejemplo?

**Comment by ljrodriguez1** [comment]
Se demora 10 segundos mas. Igual seguiré revisando en que puedo estar fallando
