### ISSUE TITLE
[Tarea 1] Test cases hackerank

### ISSUE THREAD

**Issue by Brocoleta** [marceloarenassaavedra/IIC2283-2-21#25]
Hola, podrian habilitar poder ver los testcase >1, que tengo el testcase 0 y 1 bueno, pero al parecer los otros no me dan el optimo y nose por que

**Comment by N9199** [comment]
No podemos mostrar más test cases, ya que parte de lo que se evalúa en la tarea es la capacidad de crear algoritmos correctos, esto incluye la capacidad de debuggear y la capacidad de encontrar los errores en los algoritmos. Si necesitas más test cases te recomiendo que tú los crees y valides.
