### ISSUE TITLE
Duda little-o (prueba 2020)

### ISSUE THREAD

**Issue by VicenteMerino** [marceloarenassaavedra/IIC2283-2-21#26]
Hola, según la definición de little-o, el n_0 escogido puede ser distinto para cada c, o debe ser el mismo?
![image](https://user-images.githubusercontent.com/47841749/135366517-21dc279b-e9be-473c-a195-bdf532dc9220.png)

**Comment by VicenteMerino** [comment]
Y si es posible, nos podrian dar un ejemplo de f y g? A mi se me ocurria 1 \in o(n), donde n0 = 1/c si c <1 y n0 = 1 si c >= 1. Pero no se si n0 puede escogerse por casos o si puede estar en función del c escogido.

**Comment by marceloarenassaavedra** [comment]
> Hola, según la definición de little-o, el n_0 escogido puede ser distinto para cada c, o debe ser el mismo? ![image](https://user-images.githubusercontent.com/47841749/135366517-21dc279b-e9be-473c-a195-bdf532dc9220.png)

El valor de `n_0` puede ser distinto para cada valor de `c`, dado el orden de los cuantificadores en esta definición: 

`(para todo c)(exists n_0) ...`

Si quieres indicar que el valor de `n_0` es el mismo para todos los valores de `c`, entonces deberías usar el siguiente orden de cuantificadores:

`(exists n_0)(para todo c) ...`

Saludos!

**Comment by marceloarenassaavedra** [comment]
> Y si es posible, nos podrian dar un ejemplo de f y g? A mi se me ocurria 1 \in o(n), donde n0 = 1/c si c <1 y n0 = 1 si c >= 1. Pero no se si n0 puede escogerse por casos o si puede estar en función del c escogido.

La notación little-o se usa para indicar que una función tiene menor orden que otra. Por ejemplo, se tiene que `n` es `o(n^2)` y `log(n)` es `o(n)`.

¿Queda más claro?

**Comment by VicenteMerino** [comment]
Perfecto, muchas gracias!!
