### ISSUE TITLE
Duda en ejercicio Ayudantía 2 

### ISSUE THREAD

**Issue by Taeval** [marceloarenassaavedra/IIC2283-2-21#4]
Estaba revisando la grabación de la ayudantía 2 y en el minuto 57:50 se indica que 
![image](https://user-images.githubusercontent.com/37159657/132266498-bee20631-5121-467c-ad13-3ba438816e1f.png)

pero graficando (con Desmos):

![image](https://user-images.githubusercontent.com/37159657/132266523-8b36e414-a8e1-4aa7-892c-bfda2d77e64d.png)

Esto indica que n >= 19 para que se cumpla la desigualdad. Es esto correcto? Pregunto porque tampoco se menciona cómo se llegó a alfa = 8 y n >= 2.

**Comment by bjbarias** [comment]
Hola! Toda la razón. Eso fue un error de mi parte, y gracias por mencionarlo.
Lo importante es que para un **n** en adelante se cumple!
Gracias de nuevo!
