### ISSUE TITLE
Parte 1 tarea 1

### ISSUE THREAD

**Issue by jgespinosa10** [marceloarenassaavedra/IIC2283-2-21#5]
Hola,  acabo de leer el enunciado de la tarea 1 y no logro entender el enunciado de la primera parte, ¿podrían explicarlo un poco más profundamente por favor? Muchas gracias de antemano

**Comment by VicenteMerino** [comment]
Me sumo, a la duda. En particular no entiendo bien que quiere decir "Una de ellas es contar la cantidad de caminos que pasan por N aristas con la posibilidad de repetir aristas." Si pueden mostrar un ejemplo seria ideal.

**Comment by jgespinosa10** [comment]
Muchas gracias
Solo para clarificar, entonces el problema consiste en contar todos los posibles caminos de largo N para todo el grafo, incluyendo el caso de que se puede repetir la misma arista.

**Comment by VicenteMerino** [comment]
Profe, y como se define un camino? Que si me preguntan cuantos caminos pasa por una arista, entonces serian infinitos si acepto que un camino tenga loops o no?

**Comment by marceloarenassaavedra** [comment]
> Muchas gracias
> Solo para clarificar, entonces el problema consiste en contar todos los posibles caminos de largo N para todo el grafo, incluyendo el caso de que se puede repetir la misma arista.

Sí.

**Comment by marceloarenassaavedra** [comment]
> Profe, y como se define un camino? Que si me preguntan cuantos caminos pasa por una arista, entonces serian infinitos si acepto que un camino tenga loops o no?


Un camino se define de la forma usual para grafos, como una secuencia de nodos y arcos `n_1`, `e_1`, `n_2`, `e_2`, `n_3`, ..., `n_k`, `e_k`, `n_{k+1}` tales que la arista `e_i` conecta al nodo `n_i` con el nodo `n_{i+1}`, para cada `i` entre `1` y `k`. Nótese que el camino  `n_1`, `e_1`, `n_2`, ..., `n_k`, `e_k`, `n_{k+1}` contiene `k` aristas, y algunas de estas aristas pueden estar repetidas. 

El multigrafo de la figura 2 contiene una cantidad infinita de caminos. Esto no es un problema ya que se pide encontrar el número de caminos en el multigrafo con N aristas, donde N es la entrada, y este número siempre es finito (por ejemplo, hay 14 caminos con una arista en este multigrafo). 

Saludos!

**Comment by VicenteMerino** [comment]
Y se considera por ejemplo un camino aquel que es de la forma
n1, e1, n2, e1, n1

Es decir, la misma arista para ir de un nodo a otro?

**Comment by marceloarenassaavedra** [comment]
> Y se considera por ejemplo un camino aquel que es de la forma
> n1, e1, n2, e1, n1
> 
> Es decir, la misma arista para ir de un nodo a otro?

Sí, este es un camino válido. 

Si tienes dudas sobre si algo es un camino válido usa la definición: Un camino se define como una secuencia de nodos y arcos `n_1`, `e_1`, `n_2`, `e_2`, `n_3`, ..., `n_k`, `e_k`, `n_{k+1}` tales que la arista `e_i` conecta al nodo `n_i` con el nodo `n_{i+1}`, para cada `i` entre `1` y `k`. El camino que mencionas `n1`, `e1`, `n2`, `e1`, `n1` satisface esta definición, así que es un camino válido.
