### ISSUE TITLE
Uso de librerias.

### ISSUE THREAD

**Issue by ctronp** [marceloarenassaavedra/IIC2283-2-21#6]
Hola, Tengo la duda de si se puede usar librerias como numpy para el calculo de la tabla (ejercicio 1 de la tarea 1)... probablemente quede comentado para la entrega final, pero deseo usarlo para el calculo de la tabla.

**Comment by N9199** [comment]
Para la entrega no pueden usar librerías más allá de librería standard de Python3.

**Comment by ctronp** [comment]
Okay Gracias

**Comment by N9199** [comment]
En respuesta a las que aparecieron en #16 y #22, aquí está el link a la documentación oficial de la [standard library de Python 3](https://docs.python.org/3/library/).
