### ISSUE TITLE
[Tarea 1] Tipo de solución pregunta 1

### ISSUE THREAD

**Issue by VicenteMerino** [marceloarenassaavedra/IIC2283-2-21#8]
Hola, sobre la pregunta 1 es estrictamente necesario que la solución utilice programacion dinamica? Me parece que logre una solucion en log(n) pero no utilice esta técnica en la versión final. Es valido esto?

**Comment by marceloarenassaavedra** [comment]
No es obligatorio utilizar programación dinámica. Si tienes una solución que funciona dentro del tiempo de ejecución esperado, entonces está bien aunque no apliques programación dinámica.

Saludos!
